import { useState } from "react";
import Head from "next/head";

export default function ImageGenerator() {
  const [prompt, setPrompt] = useState("");
  const [imageUrl, setImageUrl] = useState("");
  const [loading, setLoading] = useState(false);

  async function generateImage() {
    if (!prompt.trim()) return;
    setLoading(true);
    setImageUrl("");

    try {
      const res = await fetch("/api/gen-image", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ prompt }),
      });

      const data = await res.json();
      if (data?.image) {
        setImageUrl(data.image);
      } else {
        setImageUrl("error");
      }
    } catch (err) {
      setImageUrl("error");
    } finally {
      setLoading(false);
    }
  }

  return (
    <>
      <Head><title>🎨 AI Image Generator</title></Head>
      <main className="p-6 max-w-2xl mx-auto min-h-screen bg-white">
        <h1 className="text-3xl font-bold mb-6">🎨 Generate with Mixtral</h1>
        <div className="flex gap-2 mb-4">
          <input
            className="flex-1 p-2 border rounded-lg"
            value={prompt}
            onChange={(e) => setPrompt(e.target.value)}
            placeholder="Enter your prompt..."
          />
          <button
            className="bg-purple-600 text-white px-4 py-2 rounded-lg"
            onClick={generateImage}
            disabled={loading}
          >
            {loading ? "..." : "Generate"}
          </button>
        </div>

        {imageUrl === "error" && (
          <p className="text-red-500">❌ Failed to generate image.</p>
        )}

        {imageUrl && imageUrl !== "error" && (
          <img src={imageUrl} alt="Generated by Mixtral" className="rounded-xl shadow-lg mt-4" />
        )}
      </main>
    </>
  );
}
